### ISSUE TITLE
Is there any particular reason why the package requires base < 4.13?

### ISSUE THREAD

**Issue by zac-garby** [mitchellwrosen/termbox#1]
I'm unable to use the package because my version of GHC has a newer version of base. Is it possible to remove this limitation?

**Comment by mitchellwrosen** [comment]
Sorry, I just saw this. I'll get the bounds bumped, and a new version released :)

**Comment by mitchellwrosen** [comment]
Ok, released as [termbox-0.2.0.1](https://hackage.haskell.org/package/termbox-0.2.0.1)
